# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [14]:
import  sys
print("Python location:", sys.executable)
print("Python version", sys.version)

Python location: /home/annie/miniconda3/envs/pds/bin/python
Python version 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]


In [15]:
import numpy as np
#np.arange creates a NumPy array with values from 0 to 999,999
my_arr = np.arange(1_000_000)
#creates a Python list with values from 0 to 999,999
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

NumPy Vectorized Multiplication (my_arr * 2):
995 μs ± 36.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
111 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Interpretation of results:
-NumPy operation took 2.57 miliseconds while Python list operattion took 58.7mili seconds - NumPy runs way faster

In [16]:
help(np.arange) 
#help is used to check the function definition

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [17]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

print(f"Array 1:\n{arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}, Dimensions: {arr1.ndim}")

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 1:
[6.  7.5 8.  0.  1. ]
Shape: (5,), Dtype: float64, Dimensions: 1
Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


In [18]:
jagged_data = [[1, 2, 3], [4, 5]]
jagged_arr = np.array(jagged_data, dtype=object)

print("Jagged data list:", jagged_data)
print("NumPy array created from jagged data:\n", jagged_arr)
print("Shape:", jagged_arr.shape)
print("Dtype:", jagged_arr.dtype)

Jagged data list: [[1, 2, 3], [4, 5]]
NumPy array created from jagged data:
 [list([1, 2, 3]) list([4, 5])]
Shape: (2,)
Dtype: object


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [19]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [22]:
np.ones((3, 4)).astype(np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [23]:
str_arr = np.array(['1.25', '-9.6', '42']).astype(float)
str_arr

array([ 1.25, -9.6 , 42.  ])

#common mistakes
#ones_array_mistake = np.ones(3,4) #this will raise TypeError


In [ ]:

#np.zeroes
zeroes_array = np.zeros((2,5))
print("Array of zeroes:\n", zeroes_array)

full_Array = np.full((3, 3), 7)
print("Array filled with 7s:\n", full_Array)    


Array of zeroes:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array of zeroes:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array filled with 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [31]:

#try change value of element to other type
full_Array[0, 0] = 3.5
print("Modified array:\n", full_Array)
print("Dtype after modification:", full_Array.dtype)
print("Dtype after modification:", full_Array.dtype)


Modified array:
 [[3 7 7]
 [7 7 7]
 [7 7 7]]
Dtype after modification: int64
Dtype after modification: int64


In [34]:
full_Array[0, 1] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [35]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [38]:
print("Adding a scalar to an array (arr + arr):\n", arr + 10)

aDDING A SCALAR TO AN ARRAY (arr + arr):
 [[11. 12. 13.]
 [14. 15. 16.]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [40]:
# [DEMO] Slicing views
arr = np.arange(10)
print("Original array:", arr)

#[start:stop:step]
#start after 5, stop before 8, step not specified is defaulted to 1
arr_slice = arr[5:8]
print("Sliced array (arr[5:8]):", arr_slice)
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

# :2 -> 0:2:1 -> rows 0 to 1, step 1
# 1: -> 1:3:1 -> columns 1 to 2, step 1


Original array: [0 1 2 3 4 5 6 7 8 9]
Sliced array (arr[5:8]): [5 6 7]
Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [41]:
first_col = arr2d[:, 0]
arr2d[1] = 0

print("First column:", first_col)
print("Modified arr2d:\n", arr2d)
print("arr2d[1] shape:", arr2d[1].shape)
print("arr2d[1, :] shape:", arr2d[1, :].shape)

First column: [1 0 7]
Modified arr2d:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]
arr2d[1] shape: (3,)
arr2d[1, :] shape: (3,)


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [42]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [43]:
# 1. Select all scores where the name is NOT 'Bob'
not_bob_mask = (names != 'Bob')
not_bob_scores = scores[not_bob_mask]
print("Scores where name is NOT 'Bob':\n", not_bob_scores)

# 2. Select scores for 'Bob' or 'Will' using the `|` operator
bob_or_will_mask = (names == 'Bob') | (names == 'Will')
bob_or_will_scores = scores[bob_or_will_mask]
print("\nScores for 'Bob' or 'Will':\n", bob_or_will_scores)

# 3. Find all scores less than 80 and set them to 0
scores_copy = scores.copy()  # To avoid modifying the original
scores_copy[scores_copy < 80] = 0
print("\nScores with values < 80 set to 0:\n", scores_copy)

Scores where name is NOT 'Bob':
 [[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [ 72  80]]

Scores for 'Bob' or 'Will':
 [[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]

Scores with values < 80 set to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


In [ ]:
# Your code here


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [44]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0)) #axis 0 = y-axis
print("Sum across columns (axis=1):", arr.sum(axis=1)) #axis 1 = x-axis

Random Array:
 [[-0.084924    0.87093653  1.17072876 -0.77146769]
 [ 1.41324964 -2.11583948 -0.90187952 -0.68018821]
 [-1.04799684  1.46960175  0.78877979  0.45733991]]

Mean down rows (axis=0): [ 0.09344293  0.0748996   0.35254301 -0.33143866]
Sum across columns (axis=1): [ 1.1852736  -2.28465757  1.66772461]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [45]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [47]:
reshaped = np.arange(15).reshape(3, 5)
row_averages = reshaped.mean(axis=1)
unique_values = np.unique(arr2d)
transposed = reshaped.T

print("Reshaped array (3x5):\n", reshaped)
print("Average value of each row:", row_averages)
print("Elements in arr2d:", arr2d)
print("Distinct elements in arr2d:", unique_values)
print("Transposed array:\n", transposed)
print("Shape after transpose:", transposed.shape)

Reshaped array (3x5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Average value of each row: [ 2.  7. 12.]
Elements in arr2d: [[1 2 3]
 [0 0 0]
 [7 8 9]]
Distinct elements in arr2d: [0 1 2 3 7 8 9]
Transposed array:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
Shape after transpose: (5, 3)


In [ ]:
# Your code here
